"""
SESHAT PoC v0.1 — Data Models

This file defines the structure of all data that flows through SESHAT.

Why Pydantic?
- It validates that required fields are present
- It converts types automatically (e.g., string to int)
- It makes the code self-documenting (you can see exactly what data is expected)
- It will later help us validate LLM outputs
"""

from enum import Enum
from pydantic import BaseModel, Field


# ─────────────────────────────────────────────
# ENUMERATIONS
# ─────────────────────────────────────────────

class ApproachType(str, Enum):
    """
    Types of active learning approaches supported by the PoC.

    Using an Enum instead of a plain string prevents typos
    and makes autocomplete work in the editor.
    """
    PBL = "PBL"                          # Problem-Based Learning
    PROJECT = "PROJECT"                   # Project-Based Learning
    INQUIRY = "INQUIRY"                  # Inquiry-Based Learning
    ACTIVATION = "ACTIVATION"             # Think-Pair-Share, Exit tickets, etc.


# ─────────────────────────────────────────────
# SITUATION DESIGN (US-01, US-02)
# ─────────────────────────────────────────────

class SituationRequest(BaseModel):
    """
    What the teacher provides when asking SESHAT
    to generate an active learning situation.

    This corresponds to US-01: Create an active learning situation.
    """
    objectives: str = Field(
        description="Learning objectives (what students should know/do)"
    )
    level: str = Field(
        description="Student level (e.g., '6ème', 'Terminale', 'L1')"
    )
    discipline: str = Field(
        description="Subject area (e.g., 'Mathématiques', 'SVT')"
    )
    approach_type: ApproachType = Field(
        description="Type of active learning approach"
    )
    duration: str = Field(
        default="50 min",
        description="Expected duration (optional, defaults to 50 min)"
    )
    constraints: str = Field(
        default="",
        description="Additional constraints (material, group size, context...)"
    )


class Situation(BaseModel):
    """
    An active learning situation generated by SESHAT.

    Every field here maps to the acceptance criteria of US-01.
    The teacher can edit any of these fields before using the situation.
    """
    context: str = Field(
        description="The situation or scenario presented to students"
    )
    task: str = Field(
        description="What students are asked to do (instructions)"
    )
    deliverable: str = Field(
        default="",
        description="Expected output (report, presentation, answer...)"
    )
    duration: str = Field(
        description="Estimated time for the activity"
    )
    alignment_note: str = Field(
        description="How the situation aligns with the stated objectives"
    )


class VariantRequest(BaseModel):
    """
    What the teacher provides when asking for variants of a situation.

    This corresponds to US-02: Request variants of a situation.
    """
    original_situation: Situation = Field(
        description="The situation to create variants from"
    )
    variant_type: str = Field(
        description="Type of variant requested (e.g., 'more guided', 'more open', 'shorter', 'different context')"
    )


class VariantSet(BaseModel):
    """
    A set of 2-3 variants of a situation.

    Each variant is a full Situation object, plus a short description
    of how it differs from the original.
    """
    variants: list[Situation] = Field(
        description="The proposed variants (2-3)"
    )
    variant_descriptions: list[str] = Field(
        description="Brief description of how each variant differs"
    )


# ─────────────────────────────────────────────
# FORMATIVE ANALYSIS (US-03)
# ─────────────────────────────────────────────

class AnalysisRequest(BaseModel):
    """
    What the teacher provides when asking SESHAT to analyze
    student productions.

    This corresponds to US-03: Analyze student production(s).

    Note: productions contain student text. Per SECURITY.md,
    these are never persisted to disk.
    """
    original_task: str = Field(
        description="The task or question that was given to students"
    )
    objectives: str = Field(
        description="Learning objectives for this task"
    )
    productions: list[str] = Field(
        description="Student productions (one or more text responses)"
    )


class AnalysisResult(BaseModel):
    """
    The analysis returned by SESHAT, addressed to the teacher.

    This maps to the acceptance criteria of US-03:
    - Strengths observed
    - Difficulties / blocking points
    - Collective patterns (when multiple productions)
    - Evidence quoted from the productions

    Language is always addressed to the teacher, never to the student.
    """
    strengths: list[str] = Field(
        description="Observed strengths in the production(s)"
    )
    difficulties: list[str] = Field(
        description="Potential difficulties or blocking points"
    )
    collective_patterns: list[str] = Field(
        default_factory=list,
        description="Patterns observed across multiple productions (empty if single production)"
    )
    evidence: list[str] = Field(
        description="Quotes or references from the productions supporting the analysis"
    )
    confidence: str = Field(
        default="moderate",
        description="Confidence level of the analysis (low / moderate / high)"
    )


# ─────────────────────────────────────────────
# SCAFFOLDING (US-04)
# ─────────────────────────────────────────────

class ScaffoldingSuggestion(BaseModel):
    """
    A single scaffolding or relaunch suggestion.

    Level 1 = light question (minimal help)
    Level 2 = stronger clue
    Level 3 = near-direct guidance (but still no solution)

    The suggestion NEVER contains the final answer.
    """
    level: int = Field(
        ge=1,
        le=3,
        description="Support level: 1 (light) to 3 (strong)"
    )
    text: str = Field(
        description="The question or hint to propose to the teacher"
    )


class ScaffoldingSet(BaseModel):
    """
    An ordered set of scaffolding suggestions.

    This corresponds to US-04: Receive scaffolding & relaunch suggestions.
    The teacher chooses which (if any) to use with students.
    """
    suggestions: list[ScaffoldingSuggestion] = Field(
        description="Ordered suggestions from lightest to strongest support"
    )
    context: str = Field(
        description="What situation or analysis this scaffolding is based on"
    )